export const CREATE_NEW_MESSAGE ="CREATE_NEW_MESSAGE"
export const GET_ALL_MESSAGE ="GET_ALL_MESSAGE"
export const DELETE_MESSAGE ="DELETE_MESSAGE"
export const GET_UNREAD_COUNT = "GET_UNREAD_COUNT";
export const TOGGLE_PIN_SUCCESS = "TOGGLE_PIN_SUCCESS";
export const TOGGLE_PIN_FAILURE = "TOGGLE_PIN_FAILURE";
export const FETCH_PINNED_MESSAGES_SUCCESS = "FETCH_PINNED_MESSAGES_SUCCESS";
export const FETCH_PINNED_MESSAGES_FAILURE = "FETCH_PINNED_MESSAGES_FAILURE";