export const CREATE_NEW_MESSAGE ="CREATE_NEW_MESSAGE"
export const GET_ALL_MESSAGE ="GET_ALL_MESSAGE"
export const DELETE_MESSAGE ="DELETE_MESSAGE"
export const GET_UNREAD_COUNT = "GET_UNREAD_COUNT";
export const TOGGLE_PIN_SUCCESS = "TOGGLE_PIN_SUCCESS";
export const TOGGLE_PIN_FAILURE = "TOGGLE_PIN_FAILURE";
export const GET_PINNED_MESSAGES = "GET_PINNED_MESSAGES";
export const FETCH_PINNED_MESSAGES_SUCCESS = "FETCH_PINNED_MESSAGES_SUCCESS";
export const FETCH_PINNED_MESSAGES_FAILURE = "FETCH_PINNED_MESSAGES_FAILURE";

export const SEARCH_MESSAGES_SUCCESS = "SEARCH_MESSAGES_SUCCESS";
export const SEARCH_MESSAGES_FAILURE = "SEARCH_MESSAGES_FAILURE";

export const ADD_INTERACTION_REQUEST = 'ADD_INTERACTION_REQUEST';
export const ADD_INTERACTION_SUCCESS = 'ADD_INTERACTION_SUCCESS';
export const ADD_INTERACTION_FAILURE = 'ADD_INTERACTION_FAILURE';

export const REMOVE_INTERACTION_REQUEST = 'REMOVE_INTERACTION_REQUEST';
export const REMOVE_INTERACTION_SUCCESS = 'REMOVE_INTERACTION_SUCCESS';
export const REMOVE_INTERACTION_FAILURE = 'REMOVE_INTERACTION_FAILURE';