export const CREATE_CHAT = "CREATE_CHAT"
export const CREATE_GROUP = "CREATE_GROUP"
export const GET_USERS_CHAT = "GET_USERS_CHAT"
export const ADD_USERS_GROUP = "ADD_USERS_GROUP"
export const REMOVE_USERS_GROUP = "REMOVE_USERS_GROUP"
export const DELETE_CHAT = "DELETE_CHAT"
export const GET_CHAT = "GET_CHAT"
export const GET_CHAT_MEMBERS = "GET_CHAT_MEMBERS";
export const GET_CHAT_ERROR = "GET_CHAT_ERROR";

export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_FAILURE = "MARK_AS_READ_FAILURE";