export const CREATE_CHAT = "CREATE_CHAT"
export const CREATE_GROUP = "CREATE_GROUP"
export const GET_USERS_CHAT = "GET_USERS_CHAT"
export const ADD_USERS_GROUP = "ADD_USERS_GROUP"
export const REMOVE_USERS_GROUP = "REMOVE_USERS_GROUP"
export const DELETE_CHAT = "DELETE_CHAT"
export const GET_CHAT = "GET_CHAT"
export const GET_CHAT_MEMBERS = "GET_CHAT_MEMBERS";
export const GET_CHAT_ERROR = "GET_CHAT_ERROR";

export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_FAILURE = "MARK_AS_READ_FAILURE";

export const GET_USER_CHAT_STATUS = "GET_USER_CHAT_STATUS";
export const GET_USER_CHAT_STATUS_SUCCESS = "GET_USER_CHAT_STATUS_SUCCESS";
export const GET_USER_CHAT_STATUS_FAILURE = "GET_USER_CHAT_STATUS_FAILURE";

export const UPDATE_USER_CHAT_STATUS = "UPDATE_USER_CHAT_STATUS";
export const UPDATE_USER_CHAT_STATUS_SUCCESS = "UPDATE_USER_CHAT_STATUS_SUCCESS";
export const UPDATE_USER_CHAT_STATUS_FAILURE = "UPDATE_USER_CHAT_STATUS_FAILURE";

export const BLOCK_CHAT_STATUS = "BLOCK_CHAT_STATUS";
export const BLOCK_CHAT_STATUS_SUCCESS = "BLOCK_CHAT_STATUS_SUCCESS";
export const BLOCK_CHAT_STATUS_FAILURE = "BLOCK_CHAT_STATUS_FAILURE";

export const UNBLOCK_CHAT_STATUS = "UNBLOCK_CHAT_STATUS";
export const UNBLOCK_CHAT_STATUS_SUCCESS = "UNBLOCK_CHAT_STATUS_SUCCESS";
export const UNBLOCK_CHAT_STATUS_FAILURE = "UNBLOCK_CHAT_STATUS_FAILURE";

export const GET_USER_STATUSES_IN_CHAT = "GET_USER_STATUSES_IN_CHAT";
export const GET_USER_STATUSES_IN_CHAT_SUCCESS = "GET_USER_STATUSES_IN_CHAT_SUCCESS";
export const GET_USER_STATUSES_IN_CHAT_FAILURE = "GET_USER_STATUSES_IN_CHAT_FAILURE";